name: test_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  firebase_core: ^2.19.0
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  hyper_lint: ^0.0.1 
  icons_launcher: ^2.1.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
